[tool.mypy]
explicit_package_bases = true
python_version = "3.13"
ignore_missing_imports = true

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.black]
line-length = 100
target-version = ['py313']
