[tool.mypy]
explicit_package_bases = true
python_version = "3.13"
ignore_missing_imports = true

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.black]
line-length = 100
target-version = ['py313']

[tool.pytest.ini_options]
# Pytest configuration for PIP AI backend
addopts = [
    "--tb=short",
    "--strict-markers",
    "--disable-warnings",
]

# Test discovery
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

# Asyncio configuration
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

# Test markers
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests",
    "api: marks tests as API tests",
]

minversion = "6.0"
