name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.3"

      - name: Install dependencies & tools
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install ruff mypy

      - name: Aggressively clean caches
        run: |
          echo "Cleaning __pycache__ directories..."
          find . -path "*/__pycache__" -type d -exec rm -rf {} +
          echo "Cleaning .mypy_cache directories..."
          find . -path ".mypy_cache" -type d -exec rm -rf {} +
          echo "Cache cleaning done."

      - name: List directory contents for debugging
        run: |
          echo "--- Contents of backend/services/utils/ ---"
          ls -la backend/services/utils/
          echo "--- Contents of backend/services/utils/__pycache__/ (if it exists) ---"
          ls -la backend/services/utils/__pycache__/ || echo "__pycache__ directory does not exist or is empty"

      - name: Debug install & PATH
        run: |
          echo "--- PIP LIST ---"
          pip list
          echo "--- CHECK TOOLS ---"
          which ruff || echo "ruff NOT FOUND"
          which mypy || echo "mypy NOT FOUND"
          echo "--- PATH ---"
          echo $PATH

      - name: Lint with Ruff
        run: ruff check backend/

      - name: Type-check with MyPy
        run: mypy --cache-dir=/dev/null backend
        env:
          MYPYPATH: "." # Explicitly set MYPYPATH to the project root

      - name: Run tests
        run: pytest backend/tests --maxfail=1 --disable-warnings -q
